sonar.projectKey=samueldebarros_gestao-de-turmas-front
sonar.organization=samueldebarros
sonar.projectVersion=0.1.0
sonar.qualityGate.wait=true

sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**,.angular/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.javascript.lcov.reportPaths=coverage/gestao-turmas-front/lcov.info
sonar.coverage.exclusions=src/**/*.interface.ts,src/**/*.enum.ts,src/**/*.routes.ts,src/**/*.config.ts,src/environments/**,src/main.ts
