sonar.projectKey=samueldebarros_gestao-de-turmas-front
sonar.organization=samueldebarros

sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**,.angular/**,**/*.spec.ts
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
